allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  workerd: true
minimumReleaseAgeExclude:
  - '@hono/zod-validator@0.9.1'
  - '@lucide/angular@1.38.0'
  - '@typescript-eslint/eslint-plugin@8.69.0'
  - '@typescript-eslint/parser@8.69.0'
  - '@typescript-eslint/project-service@8.69.0'
  - '@typescript-eslint/scope-manager@8.69.0'
  - '@typescript-eslint/tsconfig-utils@8.69.0'
  - '@typescript-eslint/type-utils@8.69.0'
  - '@typescript-eslint/types@8.69.0'
  - '@typescript-eslint/typescript-estree@8.69.0'
  - '@typescript-eslint/utils@8.69.0'
  - '@typescript-eslint/visitor-keys@8.69.0'
  - typescript-eslint@8.69.0
  - daisyui@5.7.23
  - i18next@26.4.1
