allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  workerd: true
minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2201.8'
  - '@angular-devkit/core@22.1.8'
  - '@angular-devkit/schematics@22.1.8'
  - '@angular/build@22.1.8'
  - '@angular/cli@22.1.8'
  - '@angular/common@22.1.6'
  - '@angular/compiler-cli@22.1.6'
  - '@angular/compiler@22.1.6'
  - '@angular/core@22.1.6'
  - '@angular/forms@22.1.6'
  - '@angular/localize@22.1.6'
  - '@angular/platform-browser@22.1.6'
  - '@angular/platform-server@22.1.6'
  - '@angular/router@22.1.6'
  - '@angular/ssr@22.1.8'
  - '@cloudflare/workerd-darwin-64@1.20260910.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260910.1'
  - '@cloudflare/workerd-linux-64@1.20260910.1'
  - '@cloudflare/workerd-linux-arm64@1.20260910.1'
  - '@cloudflare/workerd-windows-64@1.20260910.1'
  - '@lucide/angular@1.44.0'
  - '@schematics/angular@22.1.8'
  - daisyui@5.7.34
  - miniflare@5.20260910.0-alpha
  - workerd@1.20260910.1
  - wrangler@4.131.0
  - zod@4.6.1
